name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build for Linux amd64
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -ldflags="-s -w" -o audiobook-processor-linux-amd64 main.go

    - name: Build for Linux arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -ldflags="-s -w" -o audiobook-processor-linux-arm64 main.go

    - name: Build for Windows amd64
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -ldflags="-s -w" -o audiobook-processor-windows-amd64.exe main.go

    - name: Build for Windows arm64
      env:
        GOOS: windows
        GOARCH: arm64
      run: go build -ldflags="-s -w" -o audiobook-processor-windows-arm64.exe main.go

    - name: Build for macOS amd64
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -ldflags="-s -w" -o audiobook-processor-macos-amd64 main.go

    - name: Build for macOS arm64
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -ldflags="-s -w" -o audiobook-processor-macos-arm64 main.go

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          audiobook-processor-linux-amd64
          audiobook-processor-linux-arm64
          audiobook-processor-windows-amd64.exe
          audiobook-processor-windows-arm64.exe
          audiobook-processor-macos-amd64
          audiobook-processor-macos-arm64